### ISSUE TITLE
DevUI Card

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-temporal#11]
Start simple at first and then we can see what we can add to it like links to the Temporal central UI etc?

**Comment by rmanibus** [comment]
We should also add the temporal version

**Comment by melloware** [comment]
agreed!

**Comment by melloware** [comment]
Should i work on adding this now or are you in the middle of any other changes?

**Comment by rmanibus** [comment]
you can now @melloware everything has been renamed

**Comment by melloware** [comment]
I just reported this bug to Temporal: https://github.com/temporalio/sdk-java/issues/2177

**Comment by melloware** [comment]
![image](https://github.com/user-attachments/assets/5740ff9e-31d9-4fdd-a6a4-b2c958ab8603)
