### ISSUE TITLE
Rename Annotations?

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-temporal#22]
Should `@ActivityImpl` be `@TemporalActivity` ?

Should `@WorkflowImpl` be `@TemporalWorkflow`

Just going by what he has done here: https://github.com/mostafacs/quarkus-temporal-extension

Hopefully he will join our project and help.

**Comment by ggrebert** [comment]
👍 
I don't realy like the "*Impl" naming

**Comment by rmanibus** [comment]
Sure,
I am not a fan of the impl either, I initially followed the naming present in the spring boot integration:

https://github.com/temporalio/sdk-java/blob/59c485e93f9b02984d7d141f21f0023ab70fd738/temporal-spring-boot-autoconfigure/src/main/java/io/temporal/spring/boot/WorkflowImpl.java#L34C1-L34C33

We just have to keep in mind that these annotations are echoing temporal built in annotation `@WorkflowInterface` and `@ActivityInterface`.

**Comment by ggrebert** [comment]
OK, so we can keep it like that for migration *SB->Quarkus* ;-)
but we should respect the same signature.

For SpringBoot there is an other argument:

```java
/**
   * @return Worker Task Queues to register this workflow implementation with. If Worker with the
   *     specified Task Queue is not defined in the application config, it will be created with a
   *     default config. Can be specified by a property key, e.g.: ${propertyKey}.
   */
String[] taskQueues() default {};
```

**Comment by melloware** [comment]
Ahhh yes I see i didn't realize you were trying to match their SB implementation.  I guess that is a good idea for people migrating as @ggrebert mentioned.  But yes we should try and implement what their SB does.

**Comment by rmanibus** [comment]
@ggrebert I thought about this and I don't think it makes sense to add the other argument for several reasons:

1) if the task queue name in the worker is not set, it default to the worker name, so one can simply leverage the existing worker argument to set the queue name if needed.
2) queue name is a runtime attribute, while it is certainly possible to build something around this, for now at the time of the discovery I don't know for sure the final queue name of a worker

**Comment by melloware** [comment]
After reading your latest comment about `WorkflowStub` already being an core interface i think i am back to wanting all our custom annotations to start with `@Temporal`  it just **feels** more Quarkus like.   Spring Boot be damned.
