### ISSUE TITLE
Allow workflow stub injection

### ISSUE THREAD

**Issue by rmanibus** [quarkiverse/quarkus-temporal#38]
with the current implementation, using the workflow client is a bit tedious
```
@Inject
WorkflowClient client;

public void callWorkflow(){

        WorkflowOptions options = WorkflowOptions.newBuilder()
                .setTaskQueue("workerName")
                .setWorkflowId("money-transfer-workflow")
                .build();

        MoneyTransferWorkflow workflow = client.newWorkflowStub(MoneyTransferWorkflow.class, options);
        TransactionDetails transaction = new CoreTransactionDetails("249020073", "152354872", "57c65dea-e57e-4a0a", 68);
        workflow.transfer(transaction);
}
```

What we could do to simplify the process is making the workflow stub available as a CDI bean:

```
@Inject
@WorkflowStub(worker = "workerName", workflowId = "money-transfer-workflow")
MoneyTransferWorkflow workflow;

public void callWorkflow(){

        TransactionDetails transaction = new CoreTransactionDetails("249020073", "152354872", "57c65dea-e57e-4a0a", 68);
        workflow.transfer(transaction);
}
```

**Comment by rmanibus** [comment]
I think the workflow id need to be configurable per execution, so we probably need to think about this a bit more

**Comment by rmanibus** [comment]
I think the way to go is to inject a provider like this, not sure of the naming though
```
public interface WorkflowProvider<T> {
    T getWorkflow(String workflowId);
}

```

**Comment by rmanibus** [comment]
@Inject
@WorkflowStub(worker = "workerName")
WorkflowProvider<MoneyTransferWorkflow> workflowProvider;

public void callWorkflow(){

        TransactionDetails transaction = new CoreTransactionDetails("249020073", "152354872", "57c65dea-e57e-4a0a", 68);
        workflowProvider.getWorkflow("money-transfer-workflow").transfer(transaction);
}

**Comment by tmulle** [comment]
I’m away for a 3 days so I won’t be responding. 

But yes the configuration should be CDI based. 
I can post code of how I’m using it currently in my project without cdi. 

I just have some utility classes that I do the setup in and then inject that applications scoped bean into my workflows and activities and then get the stubs that way. 

There are a lot of configuration options available on the stubs from Temporal so not sure how easy we can make them annotation based.
