### ISSUE TITLE
Workflow interface without implementation

### ISSUE THREAD

**Issue by rmanibus** [quarkiverse/quarkus-temporal#63]
The current implementation only works if both the workflow interface and the implementation are present in the same project.

More realistically in a real life project, worker code and client code would most likely be split in two different containers, and the client might not be aware of existing implementation.

constraints on the client code:

- The client needs to be aware of the queue name for a specific worker (either using redundant configuration, or another mechanism involving temporal server ?)
- The client has no way of knowing how many implementations exist for a given workflow. This imply that the `worker` parameter of the `TemporalWorkflowStub` qualifier must always be provided (with the current implementation, it is possible to omit it if only one implem is detected in the project).

**Comment by rmanibus** [comment]
at the very least, this limitation should be mentioned in the doc

**Comment by melloware** [comment]
I think @tmulle ran into this same thing when he was building his microservices so yes at the very least a WARNING in the docs

**Comment by tmulle** [comment]
Yes, that is why I have a common module that has the Activity interfaces in it that I can share between my workflow implementations. In my setup, I use what they call "remote activity workers".

This way each microservice is it's own "Activity" implementation. I just need to make the interfaces available to the Workflow implementation itself.

My workflow interfaces and implementations live in their respective services. I don't separate out the interface from the implementation. I suppose you could, but I don't have a need for that.

If you did, you could do the same thing and put them in a common module and make sure you built a Jandex on them so they are available in other modules?

I do this for some other beans that I keep in separate modules but need them in my workflows.
