### ISSUE TITLE
WorkflowClient: Add MDCContextPropagator

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-temporal#68]
For propagating the MDC log context between workflow activities.

**Comment by rmanibus** [comment]
this thread might contain useful info:

https://community.temporal.io/t/usage-of-contextpropagator-in-java-sdk/1152/3

**Comment by melloware** [comment]
yep in my demo i am working on with @tmulle he uses a Context Propagator but it needs to be plugged into the Client Options so the PR will allow us to do that.
