### ISSUE TITLE
Temporal Cloud: Support SSL

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-temporal#96]
From the docs here: https://docs.temporal.io/develop/java/temporal-clients#connect-to-temporal-cloud

```java
/ Generate an SSL context
            InputStream clientCertInputStream = new FileInputStream(clientCertPath);
            InputStream clientKeyInputStream = new FileInputStream(clientKeyPath);
            SslContext sslContext = SimpleSslContextBuilder.forPKCS8(clientCertInputStream, clientKeyInputStream).build();

            // Set the Service Stub options (SSL context and gRPC endpoint)
            WorkflowServiceStubsOptions stubsOptions = WorkflowServiceStubsOptions
                .newBuilder()
                .setSslContext(sslContext)
                .setTarget(gRPCEndpoint)
                .build();
```

**Comment by rmanibus** [comment]
is the idea to expose the cert and key as config ?

**Comment by rmanibus** [comment]
should we allow the use of a keystore ?

**Comment by rmanibus** [comment]
Also we can probably leverage the [Quarkus TLS Centralized Registry](https://quarkus.io/guides/tls-registry-reference)

I will have a look into this if I have some time over the weekend !

**Comment by melloware** [comment]
Yep my thought was the tls resigtry. I haven't thought it all the way through but thought we should support it for people using their cloud product.

**Comment by melloware** [comment]
I assigned it to you.

**Comment by melloware** [comment]
I really like this statement and it makes using the TlsRegistry a no brainer i think for this

> The TlsConfiguration object contains the key stores, trust stores, cipher suites, protocols, and other properties. It also provides a way to create an SSLContext from the configuration.

**Comment by rmanibus** [comment]
another callout: 
Temporal Service Stub option is taking a `io.grpc.netty.shaded.io.netty.handler.ssl`, when the TLS registry is providing a `javax.net.ssl.SSLContext`.

I still think it is valuable to pursue this route, but this will require some more digging

**Comment by rmanibus** [comment]
about the version, I think that quarkus 3.15 is around the corner and will be the next LTS. maybe we should wait for this one for our 2.0.x ?

**Comment by melloware** [comment]
ok great idea.  for now we can just add two config params for the certificates i have seen a lot of other extensions do this in the codebase.  Then maybe we switch to TLS Registry in 3.15?

**Comment by rmanibus** [comment]
I have been exploring options, and I am starting to wonder if implementing our own SSL config is the right direction.

Instead, we could inject a managed channel into the temporal client. This way, the TLS config would be done within the quarkus grpc extension directly.

But I would love some feedback from the folks contributing in the quarkus GRPC space

**Comment by rmanibus** [comment]
@mkouba Any though about using a quarkus-managed channel in the temporal client ?

The setChannel method documentation of the temporal client mention:

> Sets fully custom user-configured gRPC channel to use.
> Before supplying a fully custom channel using this method, it's recommended to first consider using setTarget(String) + other options of WorkflowServiceStubsOptions. Builder + setChannelInitializer(Consumer) for some rarely used configuration. This option is not intended for the majority of users as it disables some Temporal connection management features and can lead to outages if the channel is configured or managed improperly.
> Mutually exclusive with setTarget(String), setChannelInitializer(Consumer), setSslContext(SslContext), setGrpcReconnectFrequency(Duration) and setConnectionBackoffResetFrequency(Duration). These options are ignored if the custom channel is supplied.

**Comment by rmanibus** [comment]
it is mostly working, the only things that stand out is that we would need to map
quarkus.temporal.target to quarkus.grpc.clients.temporal-client.host and quarkus.grpc.clients.temporal-client.port

**Comment by rmanibus** [comment]
Is there a build item that can be used to set a value to a config property ?

**Comment by melloware** [comment]
Nice.  As far as your config item question I am pretty sure they are meant to be read only and not changed by anything but I could be wrong. I will let the experts weigh in.

**Comment by melloware** [comment]
Actually let me look i think i did see somewhere recently they were updating a config item.

**Comment by melloware** [comment]
@rmanibus should we add a documentation section on how to connect to Temporal Cloud using the GRCP certificate?

**Comment by shrikanthkr** [comment]
We are trying to use temporal cloud from quarkus via this extension. I have the latest version 0.0.9. Anyways I could use client cert path and client key to be used? 
I have they secrets stored in aws secrets, also finding a challenge on how to bring it in.  Any help or workarounds would be of great use.

**Comment by rmanibus** [comment]
hey @shrikanthkr, I will break a new release today.
You have two way of doing this:

- use a quarkus managed channel, and configure TLS via quarkus grpc (quarkus.grpc.clients.temporal-client ...) : https://quarkus.io/guides/grpc-reference#configuring-mtls
- using the build in channel, the new version expose quarkus.temporal.client-cert-path and quarkus.temporal.client-key-path

**Comment by rmanibus** [comment]
note that this is still an early release, I would love to get your feedback on using it in real life !

**Comment by melloware** [comment]
We also need to add this to our docs because others will ask the same thing

**Comment by melloware** [comment]
@shrikanthkr also you can use Amazon Secrets Manager to bring in your secrets: https://docs.quarkiverse.io/quarkus-amazon-services/dev/amazon-secretsmanager.html

**Comment by melloware** [comment]
@all-contributors add @shrikanthkr for testing

**Comment by shrikanthkr** [comment]
@rmanibus @melloware Thank you. I will try it out and let you know if I come across any chanllenges. Thank you so much for the quick response.

**Comment by shrikanthkr** [comment]
@melloware I tried the 0.0.10 version today. Having the mlts certpath and certkey locally on resources folder works. Am trying to figure out a way to get it from aws secrets directly. 
Overall connections to temporal cloud and worker processing it via quarkus works.

**Comment by melloware** [comment]
@shrikanthkr awesome news!!!  As for AWS secret this post has example code on how to get those vlaues as AWS Secrets: https://github.com/quarkiverse/quarkus-amazon-services/issues/510
